### ISSUE TITLE
Make Paywall Purchase Option Title & Description Dynamic

### ISSUE THREAD

**Issue by tomasstark** [laterpay/revenue-generator#261] opened 2020-09-17 15:21 UTC
We have received feedback along these lines several times (with both the LaterPay & Revenue Generator Plugins)

> Started a new paywall and wanted to change the ‘1 Month’ subscription option to ‘1 Year’I used the three dot option to change the settings but that didn’t change any of the text in the menu.I was able to manually change the text to read “1 Year Subscription” but had no way to change the explanation text beneath it. Eventually I was able to, but it’d be nice if this text could change automatically. - James

**Steps to Reproduce**

1. Open the Revenue Generator & create a new paywall
2. Select the more options "..." menu for a Time Pass or Subscription
3. Update the time period

**Observed Result**

The Paywall Title & Description do not change

**Desired Result**

These should update to reflect the updated time period UNLESS the merchant already typed in their own custom title &/or description.

**Comment by milindmore22** [comment] 2020-09-21 13:05
Hello @tomasstark,
I need a second opinion about my appoch for this ticket, 
How about we reset title and description when user changes values from dropdown, even it is customized
If that need to be retain custom text and description, what should be the best approach compare Title and Description using Javascript with Default Gloabl Options (using regx to compare )
OR save a meta flag for title and Description marking it a custom value by uesr.

PS: I am currently working on saving Meta Flag approch but I felt like I am overdoing simple thing.

**Comment by tomasstark** [comment] 2020-09-23 06:33
@milindmore22 We decided to go with the following option:

**Auto-update default title & description and ask about custom updates**

This means whenever user changes option type or time period, we display a modal asking if they'd like us to update Title and Description automatically for them. If they agree, we update it to defaults of the item they chose. If they disagree, we keep their custom text there.

---

Example:

1. User creates a paywall with '1 Month Subscription' item.
2. They decide to change '1 Month' to '1 Year' by choosing 'Year' from the dropdown when editing the option.
3. We display the modal asking them if they'd like to update.
4. If they agree, we update the title to '1 Year Subscription' automatically.

Similarly, if they update time period only – going from '1 Month' to '3 Months' – we do the same.

---

This is the copy we'd like to use for the modal:

> Looks like you updated your time period, would you like to update your paywall to match?

**Comment by ksmoore125** [comment] 2020-09-24 17:11
@milindmore22 - I am not 100% sure if this is ready for me to check yet but in case it is, here is my feedback:
- The warning message should only be displayed if the title or description has been customized (right now it is appearing even if the title and description are the defaults)
- Right now the title & description set the period to plural when the length is greater than 1; can we leave it singular in the **Title** all cases (ie: 1 Day Pass, 2 Day Pass, 1 Month Subscription, 6 Month Subscription, etc)
  - The description should continue to work as it does today
- If I change the item type (ie: from a time pass to a subscription), the title and description change to the default for that option but the length & period do not change therefore these two are out of sync
- Can we update the warning message so that it is only displayed once; when they close the (...) more options menu?
_Right now if I change the length (ie: from 1 to 2) I get the message and then if I change the period (ie: from month to week) I get the message again which is a little annoying._
- Additionally, while testing, it seems like the change we made in https://github.com/laterpay/revenue-generator/issues/164 is no longer in effect; can you take a look? Would you like me to create a new ticket for this?

**Comment by milindmore22** [comment] 2020-09-25 06:56
@ksmoore125 

- We added a warning message on the dropdown change as per previous [comment](https://github.com/laterpay/revenue-generator/issues/261#issuecomment-697163199) this will give users a choice to use autogenerated title and description or to keep the currently used customized title and description.
- Done ( code review )
- There is one more action performed on dropdowns which reset period count ( number of days, week, month, year ) when we reset period type ( switch between day, week, month year ) I have added a delay to finish those action which is now increased to 1 second.
- As per the previous comment, we have given users the choice to keep customized title and description or autogenerate on every dropdown change.
- I am not able to reproduce this on my local, the new purchase option is still showing me only one warning message only when I hit the publish button.

cc @tomasstark

**Comment by ksmoore125** [comment] 2020-09-28 19:32
@milindmore22 - See items below

## 1) Length field not auto-selected
**Steps to Reproduce**
- Set up a new paywall
- Set the subscription to 6 Months (for example)
- Publish the Paywall & Navigate to the Paywall Dashboard
- Re-open the paywall to edit
- Expand the subscription "more options"

**Observed Result**
The drop downs show 1 Month Subscription while the title and description still read 6 Months
![image](https://user-images.githubusercontent.com/41650164/94475724-1ccec580-0195-11eb-8c9e-3d65568f7db3.png)

**Desired Result**
The correct length should be pre-selected in the dropdown

## 2) Warning message should only be displayed if the title or description has been customized
**Steps to Reproduce**
- Create a new paywall
- Add a new item to the paywall
- Note that it has defaulted to a 1 Month subscription with the default title and description
- Change the period to `Year`

**Observed Result**
The warning message is displayed
![image](https://user-images.githubusercontent.com/41650164/94476005-82bb4d00-0195-11eb-8676-88146f045d5d.png)

**Desired Result**
The warning message should only be displayed if the purchase option's Title or Description has been modified.
Below is an example of when the warning message **should** be displayed
- Add a new item to the paywall
- Customize the Title to "The best Subscription ever!!" _&/or_ customize the Description to "Buy now or risk loosing out on this amazing deal!"
- Change the period to `Year`

## 3) Changing purchase option type results in out of sync values
**Steps to Reproduce**
- Open or create a paywall
- Change a subscription to a time pass

**Observed Result**
When the subscription is changed to a Time Pass, the title & description are set to the Time Pass default but the period & duration in the more options have stayed the same. Therefore the title & description and the options are out of sync.
![image](https://user-images.githubusercontent.com/41650164/94476670-67047680-0196-11eb-9d93-9bc29e99e996.png)

**Desired Result**
These should remain in sync. Any of the following could be acceptable solutions:
- Ensure that the duration & period in the title & description continue to match (therefore only the end of the Title should change when the purchase option type is changed)
- Re-set the duration & period to the default as well so that it is obvious that everything needs to be re-set

## 4) Warning message displayed too frequently
**Steps to reproduce**
- Open or create a paywall
- Change a subscription period
- _Note that the warning is displayed_
- Change the same subscription duration
- _Note that the warning is displayed_

**Observed Result**
It is annoying to have to confirm twice in a row, while in my mind, I was really only making one change

**Desired Result**
Instead of posting the warning message when one of these dropdowns is changed, could we display it when the `More options menu` is closed (thereby showing that the merchant is done making changes to that purchase option)?

## 5) The subscription warning message is no longer displayed
_I am not sure if this is related to this ticket or to one that Tom is working on_
**Steps to reproduce**
- Open or create a paywall
- Change a subscription or time pass period or duration

**Observed Result**
The [global subscription warning message](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0) is not displayed

**Desired Result**
This warning message should continue to be displayed as it was before (it should come before the update title & description warning message)

**Comment by ksmoore125** [comment] 2020-10-08 17:42
**Product Check Notes:**
1) Length field not auto-selected ✅ 
2) Warning message should only be displayed if the title or description has been customized ⚠️ 
3) Changing purchase option type results in out of sync values ✅ 
4) Warning message displayed too frequently ✅  
5) The subscription warning message is no longer displayed ❌ 

**Remaining Issues**
## 5) The subscription warning message is no longer displayed
Upon further testing, it looks like the warning message is displayed from #19 which should have been reverted. We need the previous warning message since global vs paywall subscriptions were never implemented. 
_Let me know if you need more details._

## 6) Title & description do not auto-update
**Steps to Reproduce**
- Create a new paywall (note that you have not customized the title or description)
- Change the duration &/or time period of the subscription
- Click out of the more options menu

**Observed Result**
- Note that the warning is not displayed 🎉 
- The title and description did not automatically change either :( 

**Desired Result**
- No warning message ✅ 
- The title and description should change to match the new duration &/or time period

**Comment by milindmore22** [comment] 2020-10-09 07:30
### 5) The subscription warning message is no longer displayed.
I am a little confused on this one, As the code has been replaced by Tom
![image](https://user-images.githubusercontent.com/1132541/95553880-ea428980-0a2c-11eb-8964-70f2f33a2a0c.png)
However, I am can see a warning message as per [design](https://app.zeplin.io/project/5e3b2d056723900961109141/screen/5e4deac2497bf47c22d456e0) when I change the purchase option type from the dropdown
Can you please create a new ticket for the same and add specific details.
![image](https://user-images.githubusercontent.com/1132541/95554329-9e441480-0a2d-11eb-96a2-cf7eb425e55b.png)

### 6) Title & description do not auto-update
We have triggered auto-generate action on click of `More options menu`, which will not trigger when we click out of more option, adding the same action will on wrapper click event results in an endless loop, how about we keep the box open until it has been closed by clicking on `More options menu`
![image](https://user-images.githubusercontent.com/1132541/95555365-4ad2c600-0a2f-11eb-9603-24c0d995d678.png)

**Comment by tomasstark** [comment] 2020-10-09 08:36
Related to 5th point:

> The subscription warning message is no longer displayed

Yes, the code has been refactored in the effort to make all modals in the plugin consistent (to use [RevGenModal module](https://github.com/laterpay/revenue-generator/blob/develop/assets/src/js/utils/rev-gen-modal.js)) in the commit @milindmore22 referred to. However, that shouldn't affect when modal is supposed to show up, just its visuals.

@ksmoore125 When exactly should that modal appear? I'm happy to investigate what might have went wrong and fix it up.

**Comment by ksmoore125** [comment] 2020-10-09 18:13
I have created a [Jira ticket](https://laterpay.atlassian.net/browse/CLIENTS-888) for the subscription warning issue.

**Closed** 2020-10-14 08:37 UTC
